### ISSUE TITLE
Can I give two stars to this repo?

### ISSUE THREAD

**Issue by mikpom** [yilkalargaw/emacs-native-snippets#1]
Thank for this collection

**Comment by yilkalargaw** [comment]
Thank you @mikpom.

**Comment by mikpom** [comment]
The repo gave me a perfect quick start for tempo- template language which I am actively using for half a year so far. Maybe it is worth mentioning the repo on emacs wiki https://www.emacswiki.org/emacs/TempoMode ... there is a clear demand for some kind of repo with snippets in tempo in the discussion of the page whoever has the reputation/will to do it.
